/**
 * Summary: Action type constant
 * Description: Conatins all the ACTIONS TYPE CONSTANT
 * @author Pankaj Rana
 * @date  26.05.2019
 */

export const ADD_FEEDBACK = 'ADD_FEEDBACK';
export const REMOVE_FEEDBACK = 'REMOVE_FEEDBACK';
export const EDIT_FEEDBACK = 'EDIT_FEEDBACK';
export const SET_TEXT_FILTER = 'SET_TEXT_FILTER';
export const SORT_BY_DATE = 'SORT_BY_DATE';
export const SORT_BY_END_DATE = 'SORT_BY_END_DATE';
export const SORT_BY_ISRESOLVED = 'SORT_BY_ISRESOLVED';
export const SET_START_DATE = 'SET_START_DATE';
export const SET_END_DATE = 'SET_END_DATE';
export const SET_RESOLVED_DATE = 'SET_RESOLVED_DATE';
export const SIGN_USER = 'SIGN_USER';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const MODAL_SIGNIN = 'MODAL_SIGNIN';
export const MODAL_CLOSE = 'MODAL_CLOSE';


export const PRODUCTS_REQUEST = 'PRODUCTS_REQUEST';

export const PRODUCTS_REQUEST_SUCCESS = 'PRODUCTS_REQUEST_SUCCESS';
export const PRODUCTS_REQUEST_FAILURE = 'PRODUCTS_REQUEST_FAILURE';

export const PRODUCTS_REQUEST_DESCRIPTION_SUCCESS = 'PRODUCTS_REQUEST_DESCRIPTION_SUCCESS';
export const PRODUCTS_REQUEST_DESCRIPTION_FAILURE = 'PRODUCTS_REQUEST_DESCRIPTION_FAILURE';

export const PRODUCTS_REQUEST_DETAILS_SUCCESS = 'PRODUCTS_REQUEST_DETAILS_SUCCESS';
export const PRODUCTS_REQUEST_DETAILS_FAILURE = 'PRODUCTS_REQUEST_DETAILS_FAILURE';


export const ADD_PRODUCTS = 'ADD_PRODUCTS';
export const ADD_PRODUCT_DETAILS = 'ADD_PRODUCT_DETAILS';
export const ADD_PRODUCT_DESCRIPTIONS = 'ADD_PRODUCT_DESCRIPTIONS';

export const ADD_USER = 'ADD_USER';
export const REGISTER_USER = 'REGISTER_USER';
