/**
 * Summary: Action type constant
 * Description: Conatins all the ACTIONS TYPE CONSTANT
 * @author Prateek Jain
 * @date  10.10.2018
 */

export const SET_LOADING = 'SET_LOADING';
export const SET_CALLER_MEMBERID = 'SET_CALLER_MEMBERID';
export const SET_MEMBER_MEMBERID = 'SET_MEMBER_MEMBERID';
export const GET_TAB_INFO = 'GET_TAB_INFO';
export const RESET_TAB_INFO = 'RESET_TAB_INFO';
export const SET_MEMBER_DETAILS = 'SET_MEMBER_DETAILS';
export const SET_CALLER_DETAILS = 'SET_CALLER_DETAILS';
export const SET_MEMBER_PROFILE = 'SET_MEMBER_PROFILE';
export const SET_CARE_DETAILS = 'SET_CARE_DETAILS';
export const SET_ACTIVATION_DETAILS = 'SET_ACTIVATION_DETAILS';
export const SET_MEMBER_ACCESS_ON_DEPENDENT = 'SET_MEMBER_ACCESS_ON_DEPENDENT';
export const SET_SERCHED_MEMBERS_LIST = 'SET_SERCHED_MEMBERS_LIST';
export const SET_SERVER_SUCCESS = 'SET_SERVER_SUCCESS';
export const SET_SERVER_ERROR = 'SET_SERVER_ERROR';
export const SET_CLEAR_FORM = 'SET_CLEAR_FORM';
export const SET_MEMBER_DEPENDENTS = 'SET_MEMBER_DEPENDENTS';
export const RESET_DEPENDENT_LIST = 'RESET_DEPENDENT_LIST';
export const UPDATE_TAB_INFO = 'UPDATE_TAB_INFO';
export const SET_MESSAGE_DETAILS = 'SET_MESSAGE_DETAILS';
export const SET_MEMBER_MESSAGE_DETAILS = 'SET_MEMBER_MESSAGE_DETAILS';
export const RESET_MEMBER_DETAILS_REDUCER = 'RESET_MEMBER_DETAILS_REDUCER';
export const RESET_MEMBER_DEPENDENTS_REDUCER =
  'RESET_MEMBER_DEPENDENTS_REDUCER';
export const SET_DEFAULT_STATE_IN_REDUCER = 'SET_DEFAULT_STATE_IN_REDUCER';
export const SET_TEMPLATES_NAME = 'SET_TEMPLATES_NAME';
export const SET_TEMPLATE_LIST = 'SET_TEMPLATE_LIST';
export const SET_TEMPLATE = 'SET_TEMPLATE';
export const SET_SELECTED_MEMBERS_COUNT = 'SET_SELECTED_MEMBERS_COUNT';
export const SET_MEMBERS_LIST_BY_FAMILYID = 'SET_MEMBERS_LIST_BY_FAMILYID';
export const SET_INBOX_MESSAGE_DETAILS = 'SET_INBOX_MESSAGE_DETAILS';
export const SET_MEMBER_INBOX_MESSAGE_DETAILS =
  'SET_MEMBER_INBOX_MESSAGE_DETAILS';
export const SET_FAMILY_ID = 'SET_FAMILY_ID';
export const SET_REFERRAL_ERROR = 'SET_REFERRAL_ERROR';
export const SET_REFERRAL_DATA = 'SET_REFERRAL_DATA';
export const SET_NETWORK_ERROR_DEPENDENT_API =
  'SET_NETWORK_ERROR_DEPENDENT_API';
export const UPDATE_MEMBER_INFO = 'UPDATE_MEMBER_INFO';
export const UPDATE_WITH_NEW_MEMBER_INFO = 'UPDATE_WITH_NEW_MEMBER_INFO';
export const NEW_FIELD_UPDATE_ERROR = 'NEW_FIELD_UPDATE_ERROR';
export const NEW_FIELD_UPDATE_SUCCESS = 'NEW_FIELD_UPDATE_SUCCESS';
export const NEW_UPDATE_PHONE_NUMBER = 'NEW_UPDATE_PHONE_NUMBER';
export const NEW_UPDATE_EMAIL_ADDRESS = 'NEW_UPDATE_EMAIL_ADDRESS';
export const NEW_UPDATE_PAPERLESS_PREFERENCE =
  'NEW_UPDATE_PAPERLESS_PREFERENCE';
export const NEW_UPDATE_EMAIL_PREFERENCE = 'NEW_UPDATE_EMAIL_PREFERENCE';
export const NEW_UPDATE_SMS_PREFERENCE = 'NEW_UPDATE_SMS_PREFERENCE';
export const UPDATE_SUCCESS_MSG = 'UPDATE_SUCCESS_MSG';
export const PCP_SET_LOADING = 'PCP_SET_LOADING';
export const UPDATE_ADDRESS = 'UPDATE_ADDRESS';
export const UPDATE_ADDRESS_SUCCESS_MSG = 'UPDATE_ADDRESS_SUCCESS_MSG';
export const UPDATE_ADDRESS_FAIL = 'UPDATE_ADDRESS_FAIL';
export const SEARCH_PCP = 'SEARCH_PCP';
export const UPDATE_PCP = 'UPDATE_PCP';
export const UPDATE_PCP_DETAILS = 'UPDATE_PCP_DETAILS';
export const SET_OPEN_CHANGE_PCP_MODAL = 'SET_OPEN_CHANGE_PCP_MODAL';
export const SET_DEPENDENT_TOGGLE = 'SET_DEPENDENT_TOGGLE';
export const SEARCH_PCP_LIST_FAILURE = 'SEARCH_PCP_LIST_FAILURE';
export const SET_PCP_LIST_FAILURE = 'SET_PCP_LIST_FAILURE';
export const SEARCH_PCP_LIST_ZERO = 'SEARCH_PCP_LIST_ZERO';
export const RESET_ACCOUNT = 'RESET_ACCOUNT';
export const SET_REFERRALS_SUCCESS = 'SET_REFERRALS_SUCCESS';
export const SET_REFERRALS_FAILURE = 'SET_REFERRALS_FAILURE';
export const GET_PCP_REFERRALS_AVAILABLE = 'GET_PCP_REFERRALS_AVAILABLE';
